[package]
name = "extension-count"
version = "0.3.0"
edition = "2021"
license = "Unlicense"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"

[dev-dependencies]
tempfile = "3.12.0"
